### ISSUE TITLE
Not able to add css

### ISSUE THREAD

**Issue by mudit313** [negomi/portfolio#1]
I forked your project as I wanted to display my portfolio in the same format. But when my this github page was build it was somehow not able to get the css files. It looks something like this: 
![image](https://cloud.githubusercontent.com/assets/16251791/22843476/d8cc45f6-efff-11e6-95e7-83cafb682a9f.png)

Can you help me out with this.
Thank You

**Comment by negomi** [comment]
Hi @mudit313,

You'll need to compile the Sass to see the styles.

To start the development server, run `gulp`. Then go to `http://localhost:8080` in your browser.

Let me know if you're still having problems :)
