### ISSUE TITLE
Bower.json is not available

### ISSUE THREAD

**Issue by iMahesh** [negomi/portfolio#4]
You've done a great job but there are some **bower dependencies** in **gulpfile.js** 
Please include 
> bower.json 

for convenience 

And one more issue in `sass/partials/_projects.scss @ line90` 
`@include desktop {
    @extend %center--absolute;
  }`

**Comment by negomi** [comment]
Hey @iMahesh, oh yes, not sure what happened there!

This is just an old portfolio page so I'm not actively maintaining it anymore. I would merge a PR if you feel like adding a bower.json though :)

**Comment by iMahesh** [comment]
@negomi I've added bower.json and fixed issues with sass compiler. It's working just fine right now 
I am ready to push it. Make me a contributor so that I can push it right away to a branch.

**Comment by negomi** [comment]
Cool, easiest if you open a PR that I can check out/merge :)

**Comment by iMahesh** [comment]
I've opened a PR @negomi please feel free to review the changes.

**Comment by negomi** [comment]
Fixed by https://github.com/negomi/portfolio/pull/5
